// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: rpc/server.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockLists    []string               `protobuf:"bytes,1,rep,name=blockLists,proto3" json:"blockLists,omitempty"`
	TimeSeconds   int32                  `protobuf:"varint,2,opt,name=timeSeconds,proto3" json:"timeSeconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewSessionRequest) Reset() {
	*x = NewSessionRequest{}
	mi := &file_rpc_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewSessionRequest) ProtoMessage() {}

func (x *NewSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewSessionRequest.ProtoReflect.Descriptor instead.
func (*NewSessionRequest) Descriptor() ([]byte, []int) {
	return file_rpc_server_proto_rawDescGZIP(), []int{0}
}

func (x *NewSessionRequest) GetBlockLists() []string {
	if x != nil {
		return x.BlockLists
	}
	return nil
}

func (x *NewSessionRequest) GetTimeSeconds() int32 {
	if x != nil {
		return x.TimeSeconds
	}
	return 0
}

type BlockList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Domains       []string               `protobuf:"bytes,2,rep,name=domains,proto3" json:"domains,omitempty"`
	Processes     []string               `protobuf:"bytes,3,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockList) Reset() {
	*x = BlockList{}
	mi := &file_rpc_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockList) ProtoMessage() {}

func (x *BlockList) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockList.ProtoReflect.Descriptor instead.
func (*BlockList) Descriptor() ([]byte, []int) {
	return file_rpc_server_proto_rawDescGZIP(), []int{1}
}

func (x *BlockList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BlockList) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *BlockList) GetProcesses() []string {
	if x != nil {
		return x.Processes
	}
	return nil
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeSeconds   int32                  `protobuf:"varint,1,opt,name=timeSeconds,proto3" json:"timeSeconds,omitempty"`
	BlockLists    []*BlockList           `protobuf:"bytes,2,rep,name=blockLists,proto3" json:"blockLists,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_rpc_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_rpc_server_proto_rawDescGZIP(), []int{2}
}

func (x *Session) GetTimeSeconds() int32 {
	if x != nil {
		return x.TimeSeconds
	}
	return 0
}

func (x *Session) GetBlockLists() []*BlockList {
	if x != nil {
		return x.BlockLists
	}
	return nil
}

func (x *Session) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SessionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionList) Reset() {
	*x = SessionList{}
	mi := &file_rpc_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionList) ProtoMessage() {}

func (x *SessionList) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionList.ProtoReflect.Descriptor instead.
func (*SessionList) Descriptor() ([]byte, []int) {
	return file_rpc_server_proto_rawDescGZIP(), []int{3}
}

func (x *SessionList) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

var File_rpc_server_proto protoreflect.FileDescriptor

const file_rpc_server_proto_rawDesc = "" +
	"\n" +
	"\x10rpc/server.proto\x12\afreedxm\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"U\n" +
	"\x11NewSessionRequest\x12\x1e\n" +
	"\n" +
	"blockLists\x18\x01 \x03(\tR\n" +
	"blockLists\x12 \n" +
	"\vtimeSeconds\x18\x02 \x01(\x05R\vtimeSeconds\"W\n" +
	"\tBlockList\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\adomains\x18\x02 \x03(\tR\adomains\x12\x1c\n" +
	"\tprocesses\x18\x03 \x03(\tR\tprocesses\"\x99\x01\n" +
	"\aSession\x12 \n" +
	"\vtimeSeconds\x18\x01 \x01(\x05R\vtimeSeconds\x122\n" +
	"\n" +
	"blockLists\x18\x02 \x03(\v2\x12.freedxm.BlockListR\n" +
	"blockLists\x128\n" +
	"\tcreatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\";\n" +
	"\vSessionList\x12,\n" +
	"\bsessions\x18\x01 \x03(\v2\x10.freedxm.SessionR\bsessions2\xdd\x01\n" +
	"\aService\x12C\n" +
	"\rCreateSession\x12\x1a.freedxm.NewSessionRequest\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\rFetchSessions\x12\x16.google.protobuf.Empty\x1a\x14.freedxm.SessionList\x12N\n" +
	"\x16FetchConfigFileContent\x12\x16.google.protobuf.Empty\x1a\x1c.google.protobuf.StringValueB\bZ\x06rpc/pbb\x06proto3"

var (
	file_rpc_server_proto_rawDescOnce sync.Once
	file_rpc_server_proto_rawDescData []byte
)

func file_rpc_server_proto_rawDescGZIP() []byte {
	file_rpc_server_proto_rawDescOnce.Do(func() {
		file_rpc_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_server_proto_rawDesc), len(file_rpc_server_proto_rawDesc)))
	})
	return file_rpc_server_proto_rawDescData
}

var file_rpc_server_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_server_proto_goTypes = []any{
	(*NewSessionRequest)(nil),      // 0: freedxm.NewSessionRequest
	(*BlockList)(nil),              // 1: freedxm.BlockList
	(*Session)(nil),                // 2: freedxm.Session
	(*SessionList)(nil),            // 3: freedxm.SessionList
	(*timestamppb.Timestamp)(nil),  // 4: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),          // 5: google.protobuf.Empty
	(*wrapperspb.StringValue)(nil), // 6: google.protobuf.StringValue
}
var file_rpc_server_proto_depIdxs = []int32{
	1, // 0: freedxm.Session.blockLists:type_name -> freedxm.BlockList
	4, // 1: freedxm.Session.createdAt:type_name -> google.protobuf.Timestamp
	2, // 2: freedxm.SessionList.sessions:type_name -> freedxm.Session
	0, // 3: freedxm.Service.CreateSession:input_type -> freedxm.NewSessionRequest
	5, // 4: freedxm.Service.FetchSessions:input_type -> google.protobuf.Empty
	5, // 5: freedxm.Service.FetchConfigFileContent:input_type -> google.protobuf.Empty
	5, // 6: freedxm.Service.CreateSession:output_type -> google.protobuf.Empty
	3, // 7: freedxm.Service.FetchSessions:output_type -> freedxm.SessionList
	6, // 8: freedxm.Service.FetchConfigFileContent:output_type -> google.protobuf.StringValue
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_server_proto_init() }
func file_rpc_server_proto_init() {
	if File_rpc_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_server_proto_rawDesc), len(file_rpc_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_server_proto_goTypes,
		DependencyIndexes: file_rpc_server_proto_depIdxs,
		MessageInfos:      file_rpc_server_proto_msgTypes,
	}.Build()
	File_rpc_server_proto = out.File
	file_rpc_server_proto_goTypes = nil
	file_rpc_server_proto_depIdxs = nil
}
